version: "3"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
      - "8080:8080"
    networks:
      - swarm_network
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ZOO_ENABLE_AUTH=yes
      - KAFKA_ZOOKEEPER_USER=zookeeper
      - KAFKA_ZOOKEEPER_PASSWORD=zookeeper

  broker:
    image: docker.io/bitnami/kafka:2.8.0-debian-10-r84
    ports:
      - "9093:9093"
      - "9092"
    volumes:
      - "broker_data:/bitnami"
    networks:
      - swarm_network
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CLIENT_USERS=kafka
      - KAFKA_CLIENT_PASSWORDS=kafka
      - KAFKA_HEAP_OPTS=-Xmx1024m -Xms1024m
      - KAFKA_ZOOKEEPER_USER=zookeeper
      - KAFKA_ZOOKEEPER_PASSWORD=zookeeper
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INSIDE://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INSIDE://broker:9092,EXTERNAL://127.0.0.1:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
    depends_on:
      - zookeeper

  consumer:
    build:
      context: consumer
    networks:
      - swarm_network
    environment:
      - BROKERS_URL=broker:9092
      - CLIENT_ID=clients
      - GROUP_ID=consumers
      - TOPIC=topic

  producer:
    build:
      context: producer
    networks:
      - swarm_network
    environment:
      - BROKERS_URL=broker:9092
      - CLIENT_ID=clients
      - TOPIC=topic
      - PARTITIONS=10

networks:
  swarm_network:

volumes:
  broker_data:
    driver: local
  zookeeper_data:
    driver: local